-- RecoverAI — AI Revenue Recovery Agent
-- MySQL schema

CREATE DATABASE IF NOT EXISTS recoverai CHARACTER SET utf8mb4;
USE recoverai;

-- ---------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    name                VARCHAR(120) NOT NULL,
    email               VARCHAR(160) NOT NULL,
    phone               VARCHAR(30),
    total_spent         DECIMAL(12,2) DEFAULT 0,
    successful_payments INT DEFAULT 0,
    failed_payments     INT DEFAULT 0,
    avg_order           DECIMAL(12,2) DEFAULT 0,
    risk_level          ENUM('Low','Medium','High') DEFAULT 'Low',
    repeat_customer     BOOLEAN DEFAULT FALSE,
    last_payment_at     DATETIME,
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- Payments  (Razorpay failure events land here via webhook)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    razorpay_payment_id VARCHAR(64) NOT NULL,
    customer_id         INT NOT NULL,
    amount              DECIMAL(12,2) NOT NULL,
    failure_reason      ENUM('Bank Declined','Network Error','Authentication Failed',
                              'Insufficient Funds','Human Support','Other') NOT NULL,
    attempts            INT DEFAULT 1,
    recovery_score      INT DEFAULT 0,             -- 0-100, produced by AI model
    status              ENUM('High','Medium','Low') DEFAULT 'Low',  -- recovery confidence bucket
    recovery_state      ENUM('Pending','In Progress','Recovered','Lost') DEFAULT 'Pending',
    failed_at           DATETIME NOT NULL,
    recovered_at        DATETIME NULL,
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- AI Recovery Agent activity log / decision timeline
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_activity (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    payment_id          INT NOT NULL,
    activity            VARCHAR(255) NOT NULL,
    activity_type       ENUM('analysis','decision','action','message') DEFAULT 'analysis',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- AI Recommendations (strategy + reasoning generated by Gemini/LLM)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_recommendations (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    payment_id          INT NOT NULL,
    strategy            VARCHAR(60) NOT NULL,       -- Payment Retry / Smart Reminder / Incentive Offer / Human Support
    reasoning           TEXT,
    message_draft       TEXT,
    confidence          INT DEFAULT 0,
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- Recovery Campaigns
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS campaigns (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    name                VARCHAR(150) NOT NULL,
    target_audience     VARCHAR(120),                -- e.g. High Value / Weekend / Low value
    strategy            VARCHAR(60),                 -- Payment Retry / Smart Reminder / etc
    customer_count      INT DEFAULT 0,
    potential_revenue   DECIMAL(14,2) DEFAULT 0,
    recovered_revenue   DECIMAL(14,2) DEFAULT 0,
    status              ENUM('Draft','Running','Completed','Paused') DEFAULT 'Draft',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS campaign_payments (
    campaign_id         INT NOT NULL,
    payment_id          INT NOT NULL,
    PRIMARY KEY (campaign_id, payment_id),
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- Settings (recovery rules, notifications, integrations)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
    setting_key         VARCHAR(80) PRIMARY KEY,
    setting_value       VARCHAR(255) NOT NULL,
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO settings (setting_key, setting_value) VALUES
 ('auto_analyze_failed_payments', 'true'),
 ('prioritize_high_value', 'true'),
 ('automated_reminders', 'true'),
 ('automated_recovery_actions', 'true'),
 ('minimum_payment_amount', '500'),
 ('maximum_recovery_attempts', '3'),
 ('recovery_score_threshold', '70'),
 ('retry_after_hours', '24'),
 ('razorpay_key_id', ''),
 ('razorpay_key_secret', ''),
 ('razorpay_webhook_secret', ''),
 ('gemini_api_key', ''),
 ('notify_email', 'true'),
 ('notify_sms', 'false'),
 ('notify_slack', 'false'),
 -- Business input used by /api/analytics to compute ROI (recovered revenue
 -- vs. cost of running recovery attempts). Edit this value directly in the
 -- table (or via POST /api/settings) to match your real cost per attempt —
 -- the Analytics ROI figure recalculates from whatever is stored here.
 ('cost_per_recovery_attempt', '15'),
 ('business_name', 'RecoverAI Demo Business'),
 ('admin_email', 'priyal@recoverai.app')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
